name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+3
  image: ^3.0.1
  image_picker: ^0.8.7
  http: ^0.13.6
  intl: ^0.18.0
  logger: ^1.4.0
  english_words: ^4.0.0
  provider: ^6.0.0
  graphql_flutter: ^5.1.2
  rflutter_alert: ^2.0.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true